---
- name: Set the floating ip for the capi mgmt cluster bootstrap vm
  openstack.cloud.floating_ip:
    interface: "{{ os_endpoint_type | default('public') }}"
    state: present
    network: "{{ ext_net_id }}"
    fixed_address: "{{ capi_cluster_port_ips[0] }}"
    server: "{{ capi_mgmt_cluster_instances[0].name }}"
    wait: true
  register: _capi_bootstrap_vm_fip

- name: add the bootstrap vm to the ansible inventory
  ansible.builtin.add_host:
    name: "{{ _capi_bootstrap_vm_fip.floating_ip.floating_ip_address }}"
    groups: 'capi_mgmt_bootstrp_vm'
    ansible_ssh_host: "{{ _capi_bootstrap_vm_fip.floating_ip.floating_ip_address }}"
    ansible_ssh_user: 'ubuntu'
    ansible_ssh_private_key_file: "{{ capi_mgmt_cluster_keypair.path }}"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
